import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { SOCIAL_PROOF, WHAT_HAPPENS_NEXT, getMarketHeroImage } from '../../shared/socialProofMetrics.ts';

// Seed function: creates EmailTemplate records for all 51 email variations.
// Idempotent — skips slugs that already exist.
// Run once on deploy via the admin UI or dashboard.

const ADMIN_HUB = 'https://100c-os.base44.app/AdminHub';
const PORTAL_URL = 'https://the100collection.com/portal/properties';
const CAREERS_URL = 'https://theonehundredcollection.com/careers';
const ACCEPT_URL = 'https://100c-os.base44.app/portal/accept-invite?token=preview-token';
const REVIEW_URL = 'https://100c-os.base44.app/admin/review/preview-sub-001';
const MOCK_PROPERTY_HERO = 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&auto=format&fit=crop&q=80';
const MOCK_DESTINATION_HERO = getMarketHeroImage('Nags Head');

const TEMPLATES = [
  // ══ Partner-facing (9) ════════════════════════════════════════════════
  {
    slug: 'activation-new-partner', name: 'Activation email (new partner)', category: 'Partner-facing', urgency: 'success',
    description: 'Sent when a new partner is activated and invited to set up their portal account.',
    trigger_function: 'sendActivationEmail',
    event_tag: 'WELCOME TO THE COLLECTION',
    headline: 'Welcome to your 100 Collection Partner Portal',
    subheadline: 'Your account for {{partner.partner_name}} is ready.',
    context_block: 'Hi {{application.first_name}}, your portal is one place for every part of your relationship with The 100 Collection: manage your properties, view billing and licensing, post open roles, and update your public profile shown on theonehundredcollection.com.',
    cta_label: 'Activate my portal', cta_url: ACCEPT_URL,
    footer_note: 'This link expires in 14 days.',
    subject: 'Welcome to your 100 Collection Partner Portal',
    hero_image_url: MOCK_DESTINATION_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.activation,
    social_proof: SOCIAL_PROOF.activation,
    reply_prompt_enabled: true,
  },
  {
    slug: 'activation-existing-partner', name: 'Activation email (existing-partner access)', category: 'Partner-facing', urgency: 'success',
    description: 'Sent when a user requests and is granted access to an existing partner portal.',
    trigger_function: 'sendActivationEmail',
    event_tag: 'WELCOME TO THE COLLECTION',
    headline: 'You have been granted portal access',
    subheadline: 'Your access to {{partner.partner_name}} is ready.',
    context_block: 'Hi {{application.first_name}}, you can now manage properties, view billing, post jobs, and update your public profile.',
    cta_label: 'Activate my portal', cta_url: ACCEPT_URL,
    footer_note: 'This link expires in 14 days.',
    subject: 'Your 100 Collection portal access is ready',
    hero_image_url: MOCK_DESTINATION_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.activation,
    social_proof: SOCIAL_PROOF.activation,
    reply_prompt_enabled: true,
  },
  {
    slug: 'teammate-invitation', name: 'Teammate invitation', category: 'Partner-facing', urgency: 'info',
    description: 'Sent when a primary contact invites a teammate to join the partner portal.',
    trigger_function: 'sendActivationEmail',
    event_tag: "YOU'RE INVITED",
    headline: "You're Invited",
    subheadline: 'Join {{partner.partner_name}} on The 100 Collection Partner Portal.',
    context_block: '{{inviter.name}} has invited you to join {{partner.partner_name}}\'s team on the 100 Collection Partner Portal. Click below to accept and create your account.',
    cta_label: 'Accept Invitation', cta_url: ACCEPT_URL,
    footer_note: 'This invitation expires in 14 days.',
    subject: "You're invited to {{partner.partner_name}}'s 100 Collection Partner Portal",
    reply_prompt_enabled: false,
  },
  {
    slug: 'property-approved', name: 'Property approved (celebratory)', category: 'Partner-facing', urgency: 'success',
    description: "Sent when a property submission is approved. Celebratory tone with property name in subject.",
    trigger_function: 'sendPropertyEmail',
    event_tag: 'WELCOME TO THE COLLECTION',
    headline: 'Welcome to the Collection',
    subheadline: '{{property.property_name}} has been approved.',
    context_block: 'This is a milestone moment for {{partner.partner_name}}. Your property is now officially part of The 100 Collection, and we\'re thrilled to have it. Our licensing team will be in touch within 48 hours to finalize the details, and your listing will be live on theonehundredcollection.com shortly after. Located in {{property.location}}.',
    cta_label: 'View in Your Portal', cta_url: PORTAL_URL,
    footer_note: 'Cheers to the beginning of a great partnership. — The 100 Collection Team',
    subject: '{{property.property_name}} is joining The 100 Collection',
    hero_image_url: MOCK_PROPERTY_HERO,
    reply_prompt_enabled: true,
  },
  {
    slug: 'property-needs-revision', name: 'Property submission needs revision', category: 'Partner-facing', urgency: 'warning',
    description: 'Sent when a property submission needs revisions before it can be approved.',
    trigger_function: 'sendPropertyEmail',
    event_tag: 'REVISIONS REQUESTED',
    headline: 'Revisions Requested for {{property.property_name}}',
    subheadline: '{{property.location}}',
    context_block: 'Our curation team has reviewed {{property.property_name}} and has the following feedback:',
    callout: '{{submission.partner_facing_message}}',
    cta_label: 'View Feedback', cta_url: PORTAL_URL,
    footer_note: '— The 100 Collection Team',
    subject: 'Revisions requested for {{property.property_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'property-rejected', name: 'Property rejected (respectful)', category: 'Partner-facing', urgency: 'alert',
    description: 'Sent when a property submission is not selected. Respectful tone with property name in subject.',
    trigger_function: 'sendPropertyEmail',
    event_tag: 'UPDATE ON YOUR SUBMISSION',
    headline: 'Update on your submission',
    subheadline: '{{property.property_name}} - {{property.location}}',
    context_block: 'After careful review, our curation team has decided that {{property.property_name}} is not the right fit for The 100 Collection at this time. We appreciate the time and detail you shared with us. If your circumstances change or you\'d like feedback, please reach out.',
    callout: '{{submission.partner_facing_message}}',
    cta_label: 'Return to Portal', cta_url: PORTAL_URL,
    footer_note: '— The 100 Collection Team',
    subject: 'An update on {{property.property_name}} at The 100 Collection',
    reply_prompt_enabled: false,
  },
  {
    slug: 'property-under-review', name: 'Property submission under review', category: 'Partner-facing', urgency: 'default',
    description: 'Sent when a property submission enters the review queue.',
    trigger_function: 'sendPropertyEmail',
    event_tag: 'UNDER REVIEW',
    headline: '{{property.property_name}} is Now Under Review',
    subheadline: '{{property.location}}',
    context_block: 'Your property {{property.property_name}} is now being reviewed by our curation team. We\'ll be in touch soon with an update.',
    footer_note: '— The 100 Collection Team',
    subject: '{{property.property_name}} is now under review',
    reply_prompt_enabled: false,
  },
  {
    slug: 'property-edit-approved', name: 'Property edit request approved', category: 'Partner-facing', urgency: 'success',
    description: 'Sent when a partner edit request is approved.',
    trigger_function: 'sendPropertyEmail',
    event_tag: 'WELCOME TO THE COLLECTION',
    headline: 'Welcome to the Collection',
    subheadline: '{{property.property_name}} has been approved.',
    context_block: 'This is a milestone moment for {{partner.partner_name}}. Your property is now officially part of The 100 Collection, and we\'re thrilled to have it. Our licensing team will be in touch within 48 hours to finalize the details, and your listing will be live on theonehundredcollection.com shortly after. Located in {{property.location}}.',
    cta_label: 'View in Your Portal', cta_url: PORTAL_URL,
    footer_note: 'Cheers to the beginning of a great partnership. — The 100 Collection Team',
    subject: '{{property.property_name}} is joining The 100 Collection',
    hero_image_url: MOCK_PROPERTY_HERO,
    reply_prompt_enabled: true,
  },
  {
    slug: 'property-edit-rejected', name: 'Property edit request rejected', category: 'Partner-facing', urgency: 'alert',
    description: 'Sent when a partner edit request is rejected.',
    trigger_function: 'sendPropertyEmail',
    event_tag: 'UPDATE ON YOUR SUBMISSION',
    headline: 'Update on your submission',
    subheadline: '{{property.property_name}} - {{property.location}}',
    context_block: 'After careful review, our curation team has decided that {{property.property_name}} is not the right fit for The 100 Collection at this time.',
    callout: '{{submission.partner_facing_message}}',
    cta_label: 'Return to Portal', cta_url: PORTAL_URL,
    footer_note: '— The 100 Collection Team',
    subject: 'An update on {{property.property_name}} at The 100 Collection',
    reply_prompt_enabled: false,
  },

  // ══ Homeowner-facing (3) ══════════════════════════════════════════════
  {
    slug: 'homeowner-application-multi', name: 'Homeowner application received (multi-property)', category: 'Homeowner-facing', urgency: 'default',
    description: 'Sent to a homeowner applicant after they submit multiple properties for review.',
    trigger_function: 'onPartnerApplicationCreate',
    event_tag: 'APPLICATION RECEIVED',
    headline: 'Thank you for your application',
    subheadline: 'Your {{homeowner.properties_count}} properties are under review.',
    context_block: 'Hi {{homeowner.first_name}}, thank you for submitting your properties to The 100 Collection. We\'ve received your application and our curation team will review each property carefully. We\'ll be in touch within 1 to 2 weeks with next steps.',
    cta_label: 'Explore The 100 Collection', cta_url: 'https://theonehundredcollection.com',
    subject: 'Thank you for your application - The 100 Collection',
    hero_image_url: MOCK_DESTINATION_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.application,
    social_proof: SOCIAL_PROOF.homeowner,
    reply_prompt_enabled: true,
  },
  {
    slug: 'homeowner-batch-approved', name: 'Homeowner batch approved (all homes)', category: 'Homeowner-facing', urgency: 'success',
    description: "Sent when all of a homeowner's submitted properties are approved at once.",
    trigger_function: 'approvePropertySubmission',
    event_tag: 'WELCOME HOMEOWNER',
    headline: 'Welcome to The 100 Collection',
    subheadline: 'Your homes are joining the Collection.',
    context_block: '{{homeowner.first_name}}, all of your submitted homes have been approved. Each will receive their own editorial feature over the next 21 days. Our team will be in touch to schedule your writer interview.',
    cta_label: 'Activate my portal', cta_url: ACCEPT_URL,
    subject: 'Welcome to The 100 Collection',
    hero_image_url: MOCK_DESTINATION_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.homeowner,
    social_proof: SOCIAL_PROOF.homeowner,
    reply_prompt_enabled: true,
  },
  {
    slug: 'homeowner-per-property-approved', name: 'Homeowner single property approved', category: 'Homeowner-facing', urgency: 'success',
    description: 'Sent when an individual homeowner property is approved for the Collection.',
    trigger_function: 'approvePropertySubmission',
    event_tag: 'WELCOME TO THE COLLECTION',
    headline: '{{property.property_name}} is joining The 100 Collection',
    subheadline: 'Welcome to the Collection.',
    context_block: 'This is a special moment. Your home in {{property.location}} is now officially part of The 100 Collection. Our editorial team will be in touch within 48 hours to schedule your writer interview and start crafting your home\'s feature story.',
    cta_label: 'View in Your Portal', cta_url: PORTAL_URL,
    subject: '{{property.property_name}} is joining The 100 Collection',
    hero_image_url: MOCK_PROPERTY_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.homeowner,
    reply_prompt_enabled: true,
  },

  // ══ Candidate-facing (7) ══════════════════════════════════════════════
  {
    slug: 'application-under-review', name: 'Application under review', category: 'Candidate-facing', urgency: 'info',
    description: 'Sent when a job application is received and enters review.',
    trigger_function: 'sendJobApplicationEmail',
    event_tag: 'APPLICATION RECEIVED',
    headline: 'Application Received',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'Thank you for applying for {{candidate.job_title}} at {{partner.partner_name}}. We have received your application and our team is reviewing it now. We will be in touch soon with an update.',
    subject: 'Your application for {{candidate.job_title}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'interview-invitation', name: 'Interview invitation', category: 'Candidate-facing', urgency: 'success',
    description: 'Sent when a candidate is invited to interview.',
    trigger_function: 'sendJobApplicationEmail',
    event_tag: 'INTERVIEW INVITATION',
    headline: 'Interview Invitation',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'We have reviewed your application for {{candidate.job_title}} at {{partner.partner_name}} and would love to invite you to interview.',
    callout: 'We would like to schedule a first-round interview this week. Are you available Thursday or Friday afternoon?',
    subject: 'Interview invitation for {{candidate.job_title}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'offer-extended', name: 'Offer extended', category: 'Candidate-facing', urgency: 'success',
    description: 'Sent when a candidate is offered the role.',
    trigger_function: 'sendJobApplicationEmail',
    event_tag: 'OFFER EXTENDED',
    headline: 'We Would Like to Offer You the Role',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'We are pleased to extend an offer for {{candidate.job_title}} at {{partner.partner_name}}.',
    callout: 'We are pleased to extend an offer for the {{candidate.job_title}} role.',
    subject: 'Offer from {{partner.partner_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'hired-welcome', name: 'Hired welcome', category: 'Candidate-facing', urgency: 'success',
    description: 'Sent when a candidate accepts and is welcomed to the team.',
    trigger_function: 'sendJobApplicationEmail',
    event_tag: 'WELCOME ABOARD',
    headline: 'Welcome Aboard!',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'Welcome to the team. We are excited to have you on board for {{candidate.job_title}} at {{partner.partner_name}} and cannot wait to get started.',
    subject: 'Welcome to {{partner.partner_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'application-rejected', name: 'Application rejected', category: 'Candidate-facing', urgency: 'default',
    description: 'Sent when a candidate is not selected.',
    trigger_function: 'sendJobApplicationEmail',
    event_tag: 'APPLICATION UPDATE',
    headline: 'Application Update',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'Thank you for taking the time to apply for {{candidate.job_title}} at {{partner.partner_name}}. After careful consideration, we have decided to move forward with other candidates whose experience more closely matches what we are looking for right now. We wish you all the best in your job search and hope our paths cross again in the future.',
    callout: '{{submission.partner_facing_message}}',
    subject: 'Update on your application for {{candidate.job_title}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'position-filled-courtesy', name: 'Position filled courtesy email', category: 'Candidate-facing', urgency: 'default',
    description: 'Sent to remaining candidates when a position is filled.',
    trigger_function: 'sendPositionFilledEmails',
    event_tag: 'POSITION FILLED',
    headline: 'Position Filled',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'Thank you for your interest in the {{candidate.job_title}} role. We wanted to let you know that this position has been filled. We appreciate the time you took to apply and wish you the best in your job search. Please keep an eye on our careers page for future openings that may be a great fit.',
    cta_label: 'View Careers', cta_url: CAREERS_URL,
    subject: 'Update on your application for {{candidate.job_title}} at {{partner.partner_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'position-closed-courtesy', name: 'Position closed no-hire courtesy email', category: 'Candidate-facing', urgency: 'default',
    description: 'Sent to remaining candidates when a position is closed without hiring.',
    trigger_function: 'sendPositionFilledEmails',
    event_tag: 'POSITION CLOSED',
    headline: 'Position Closed',
    subheadline: 'Hi {{candidate.name}},',
    context_block: 'Thank you for your interest in the {{candidate.job_title}} role. We\'ve made the decision to close this position at this time. We appreciate the time you took to apply and wish you the best in your job search. Please keep an eye on our careers page for future openings.',
    callout: '{{submission.partner_facing_message}}',
    cta_label: 'View Careers', cta_url: CAREERS_URL,
    subject: 'Update on your application for {{candidate.job_title}} at {{partner.partner_name}}',
    reply_prompt_enabled: false,
  },

  // ══ Invitation acceptance (3) ════════════════════════════════════════
  {
    slug: 'invite-accepted-welcome-primary', name: 'Invitation accepted - welcome (primary)', category: 'Invitation acceptance', urgency: 'success',
    description: 'Welcome email sent to a primary contact when they accept their portal activation invitation.',
    trigger_function: 'sendInvitationAcceptedEmails',
    event_tag: "YOU'RE IN",
    headline: "You're in. Welcome to The 100 Collection.",
    subheadline: 'Your Partner Portal for {{partner.partner_name}} is now active.',
    context_block: "Hi {{application.first_name}}, you're all set. {{partner.partner_name}}'s portal is now yours to manage. From here you can add properties, view billing, post open roles, and refine your public profile. First five minutes: check that My Profile matches what you'd want travelers to see, open My Properties and confirm your active listings look right, and invite teammates from the Team page.",
    cta_label: 'Open your Portal', cta_url: PORTAL_URL,
    subject: "You're in. Welcome to The 100 Collection.",
    reply_prompt_enabled: false,
  },
  {
    slug: 'invite-accepted-welcome-teammate', name: 'Invitation accepted - welcome (teammate)', category: 'Invitation acceptance', urgency: 'success',
    description: 'Welcome email sent to a teammate when they accept their portal invitation.',
    trigger_function: 'sendInvitationAcceptedEmails',
    event_tag: 'WELCOME TO THE TEAM',
    headline: 'Welcome to the team',
    subheadline: "You've joined {{partner.partner_name}} on The 100 Collection.",
    context_block: 'Hi {{application.first_name}}, {{inviter.name}} added you to {{partner.partner_name}}\'s Partner Portal. As {{teammate.role}}, you\'ll be able to manage properties, media, careers, and the public profile. Your account is active now.',
    cta_label: 'Open your Portal', cta_url: PORTAL_URL,
    subject: "You've joined {{partner.partner_name}} on The 100 Collection",
    reply_prompt_enabled: false,
  },
  {
    slug: 'invite-accepted-fyi-inviter', name: 'Invitation accepted - FYI to inviter', category: 'Invitation acceptance', urgency: 'success',
    description: 'FYI email sent to the inviter when a teammate accepts their portal invitation.',
    trigger_function: 'sendInvitationAcceptedEmails',
    event_tag: 'TEAMMATE JOINED',
    headline: '{{teammate.name}} joined {{partner.partner_name}}',
    subheadline: '{{teammate.name}} is now active in your portal.',
    data_rows: [
      { label: 'Name', value: '{{teammate.name}}' },
      { label: 'Email', value: '{{teammate.email}}' },
      { label: 'Role', value: '{{teammate.role}}' },
    ],
    cta_label: 'View your team', cta_url: 'https://theonehundredcollection.com/portal/team',
    footer_note: 'You can adjust their role or remove them anytime from the Team page.',
    subject: '{{teammate.name}} joined {{partner.partner_name}}',
    reply_prompt_enabled: false,
  },

  // ══ Admin - Partner actions (12) ═════════════════════════════════════
  {
    slug: 'admin-new-partner-application', name: 'New partner application received', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a new partner applies to join The 100 Collection.',
    trigger_function: 'onPartnerApplicationCreate',
    event_tag: 'NEW PARTNER APPLICATION',
    headline: 'New application from {{partner.partner_name}}',
    subheadline: 'Property Manager track with 12 properties.',
    context_block: '{{application.full_name}} applied to join The 100 Collection as a property manager.',
    data_rows: [
      { label: 'Applicant', value: '{{application.full_name}}' },
      { label: 'Company', value: '{{partner.partner_name}}' },
      { label: 'Track', value: 'Property Manager' },
      { label: 'Properties', value: '12' },
      { label: 'Locations', value: 'Outer Banks, NC' },
      { label: 'Email', value: '{{application.email}}' },
      { label: 'How They Heard', value: 'Referral from existing partner' },
    ],
    cta_label: 'Review in Admin Hub', cta_url: `${ADMIN_HUB}?tab=applications`,
    subject: 'New application - {{partner.partner_name}} (Property Manager)',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-new-property-submission', name: 'New property submission received', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a partner submits a property for review.',
    trigger_function: 'onPropertySubmissionCreate',
    event_tag: 'NEW PROPERTY SUBMISSION',
    headline: '{{partner.partner_name}} submitted {{property.property_name}}',
    subheadline: 'A new property is ready for review.',
    context_block: '{{partner.partner_name}} submitted {{property.property_name}} for review.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Market', value: '{{property.location}}' },
    ],
    cta_label: 'Review Submission', cta_url: REVIEW_URL,
    subject: 'NEW PROPERTY SUBMISSION - {{property.property_name}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-new-job-posting', name: 'New job posting created', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a partner creates a job posting.',
    trigger_function: 'onJobPostingCreate',
    event_tag: 'NEW JOB POSTING',
    headline: '{{partner.partner_name}} posted a new job',
    subheadline: 'A partner posted a position for review.',
    context_block: '{{partner.partner_name}} posted "{{candidate.job_title}}" in {{property.location}}.',
    data_rows: [
      { label: 'Title', value: '{{candidate.job_title}}' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Location', value: '{{property.location}}' },
      { label: 'Type', value: 'Full Time' },
      { label: 'Department', value: 'Guest Services' },
      { label: 'Compensation', value: '$48,000 to $55,000' },
    ],
    cta_label: 'Review Posting', cta_url: 'https://100c-os.base44.app/JobApplications?tab=postings',
    subject: 'New job posting - {{candidate.job_title}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-portal-access-request', name: 'New user requesting portal access', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a user requests access to an existing partner portal (with match).',
    trigger_function: 'notifyPendingUser',
    event_tag: 'PORTAL ACCESS REQUEST',
    headline: '{{application.full_name}} requested portal access',
    subheadline: 'Top match: {{partner.partner_name}} (92% confidence)',
    context_block: '{{application.full_name}} from {{partner.partner_name}} requested access to an existing partner portal.',
    data_rows: [
      { label: 'Applicant Name', value: '{{application.full_name}}' },
      { label: 'Email', value: '{{application.email}}' },
      { label: 'Company', value: '{{partner.partner_name}}' },
      { label: 'Match Confidence', value: '92%' },
      { label: 'Matched Partner', value: '{{partner.partner_name}}' },
    ],
    cta_label: 'Review Request', cta_url: `${ADMIN_HUB}?tab=applications`,
    subject: 'Portal access request - {{application.full_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-review-note-mention', name: '@mention in review note', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when tagged in a property submission review note.',
    trigger_function: 'onReviewNoteCreate',
    event_tag: 'REVIEW NOTE',
    headline: '{{inviter.name}} mentioned you on {{property.property_name}}',
    subheadline: 'You were tagged in a review note. Open the submission to see the full context and reply.',
    context_block: 'Can you take a look at the photo quality on slide 3? I think we need to request reshoots before this goes live.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Mentioned By', value: '{{inviter.name}}' },
    ],
    cta_label: 'View Note', cta_url: REVIEW_URL,
    subject: 'You were mentioned on {{property.property_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-funnel-comment-mention', name: '@mention in funnel comment', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when tagged in an onboarding funnel thread comment.',
    trigger_function: 'onFunnelCommentCreate',
    event_tag: 'FUNNEL COMMENT',
    headline: '{{inviter.name}} tagged you on {{partner.partner_name}}',
    subheadline: 'You were tagged in an onboarding thread comment. Open the funnel tracker to see the full conversation.',
    context_block: 'The contract is signed and billing is set up. Can you kick off the listing build this week?',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Tagged By', value: '{{inviter.name}}' },
    ],
    cta_label: 'Open the thread', cta_url: 'https://100c-os.base44.app/PartnerFunnelTracker',
    subject: "You were tagged on {{partner.partner_name}}'s onboarding thread",
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-job-posting-filled', name: 'Job posting filled', category: 'Admin — Partner actions', urgency: 'success',
    description: 'Admin notification when a partner fills a job posting.',
    trigger_function: 'notifyAdminsJobPostingClosed',
    event_tag: 'JOB POSTING CLOSED',
    headline: '{{partner.partner_name}} filled {{candidate.job_title}}',
    subheadline: 'The listing is wrapped up and remaining candidates were notified.',
    context_block: '{{partner.partner_name}} marked {{candidate.job_title}} as filled and noted the hire.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Position', value: '{{candidate.job_title}}' },
      { label: 'Location', value: '{{property.location}}' },
      { label: 'Closed Reason', value: 'Position Filled' },
      { label: 'Hired Person', value: '{{candidate.name}}' },
      { label: 'Candidates Notified', value: '7' },
      { label: 'Closed By', value: '{{inviter.name}}' },
    ],
    cta_label: 'View in Admin Hub', cta_url: 'https://100c-os.base44.app/JobApplications?tab=postings',
    subject: 'Position filled - {{candidate.job_title}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-job-posting-closed', name: 'Job posting closed no-hire', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a partner closes a job posting without hiring.',
    trigger_function: 'notifyAdminsJobPostingClosed',
    event_tag: 'JOB POSTING CLOSED',
    headline: '{{partner.partner_name}} closed {{candidate.job_title}}',
    subheadline: 'The listing has been closed and pending applicants were notified.',
    context_block: '{{partner.partner_name}} closed the listing for {{candidate.job_title}}.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Position', value: '{{candidate.job_title}}' },
      { label: 'Location', value: '{{property.location}}' },
      { label: 'Closed Reason', value: 'Did not find the right fit' },
      { label: 'Candidates Notified', value: '5' },
      { label: 'Closed By', value: '{{inviter.name}}' },
    ],
    cta_label: 'View in Admin Hub', cta_url: 'https://100c-os.base44.app/JobApplications?tab=postings',
    subject: 'Position closed - {{candidate.job_title}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-property-edit-submitted', name: 'Property edit request submitted', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a partner submits an edit request for an existing property.',
    trigger_function: 'notifyAdminsPropertyEdit',
    event_tag: 'PROPERTY EDIT REQUEST',
    headline: '{{partner.partner_name}} requested edits to {{property.property_name}}',
    subheadline: 'A partner is requesting changes to an existing property.',
    context_block: '{{partner.partner_name}} submitted an edit request for {{property.property_name}}. Review the changes before approving.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Market', value: '{{property.location}}' },
      { label: 'Existing Property ID', value: 'prop-existing-001' },
    ],
    cta_label: 'Review Edit', cta_url: REVIEW_URL,
    subject: 'PROPERTY EDIT REQUEST - {{property.property_name}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-existing-partner-request', name: 'Existing-partner access request submitted', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a user requests access to an existing partner portal (no match found).',
    trigger_function: 'notifyPendingUser',
    event_tag: 'PORTAL ACCESS REQUEST',
    headline: '{{application.full_name}} requested portal access',
    subheadline: 'No confident match found. Manual review needed.',
    context_block: '{{application.full_name}} from {{partner.partner_name}} requested access to an existing partner portal.',
    data_rows: [
      { label: 'Applicant Name', value: '{{application.full_name}}' },
      { label: 'Email', value: '{{application.email}}' },
      { label: 'Company', value: '{{partner.partner_name}}' },
      { label: 'Match Confidence', value: 'No match' },
      { label: 'Matched Partner', value: '-' },
    ],
    cta_label: 'Review Request', cta_url: `${ADMIN_HUB}?tab=applications`,
    subject: 'Portal access request - {{application.full_name}}',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-teammate-joined', name: 'Teammate joined (accepted invitation)', category: 'Admin — Partner actions', urgency: 'success',
    description: 'Admin notification when a teammate accepts a portal invitation.',
    trigger_function: 'notifyAdminsInvitationAccepted',
    event_tag: 'TEAMMATE JOINED',
    headline: '{{teammate.name}} joined {{partner.partner_name}}',
    subheadline: 'A teammate accepted their portal invitation and is now active.',
    context_block: '{{teammate.name}} accepted the invitation from {{inviter.name}} and now has portal access to {{partner.partner_name}}.',
    data_rows: [
      { label: 'Teammate', value: '{{teammate.name}}' },
      { label: 'Email', value: '{{teammate.email}}' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'InvitedBy', value: '{{inviter.name}}' },
    ],
    cta_label: 'View Partner', cta_url: 'https://100c-os.base44.app/Partners',
    subject: 'Teammate joined - {{teammate.name}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-teammate-invited', name: 'Teammate invited', category: 'Admin — Partner actions', urgency: 'default',
    description: 'Admin notification when a teammate invitation is sent.',
    trigger_function: 'notifyAdminsTeammateInvited',
    event_tag: 'TEAMMATE INVITED',
    headline: '{{inviter.name}} invited a teammate to {{partner.partner_name}}',
    subheadline: 'An invitation email was sent. The teammate will appear in the portal once they accept.',
    context_block: '{{inviter.name}} sent a portal invitation to {{teammate.email}} for {{partner.partner_name}}.',
    data_rows: [
      { label: 'Invitee', value: '{{teammate.email}}' },
      { label: 'Email', value: '{{teammate.email}}' },
      { label: 'Role', value: 'Partner (pending acceptance)' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Invited By', value: '{{inviter.name}}' },
    ],
    cta_label: 'View Partner', cta_url: 'https://100c-os.base44.app/Partners',
    subject: 'Teammate invited - {{teammate.email}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },

  // ══ Admin - Financial (7) ════════════════════════════════════════════
  {
    slug: 'admin-payment-succeeded', name: 'Payment succeeded', category: 'Admin — Financial', urgency: 'success',
    description: 'Admin notification when a license payment is successfully processed.',
    trigger_function: 'notifyAdminsPaymentSucceeded',
    event_tag: 'PAYMENT RECEIVED',
    headline: 'Payment received from {{partner.partner_name}}',
    subheadline: '{{partner.partner_name}} just paid their license for {{property.property_name}}.',
    context_block: 'A payment was successfully processed for {{property.property_name}}\'s license.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Amount', value: '${{invoice.amount}}.00' },
      { label: 'Payment Method', value: 'Visa ending in 4242' },
    ],
    cta_label: 'View License', cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'Payment received - ${{invoice.amount}}.00 ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-payment-failed', name: 'Payment failed', category: 'Admin — Financial', urgency: 'alert',
    description: 'Admin notification when a license payment fails.',
    trigger_function: 'notifyAdminsPaymentFailed',
    event_tag: 'PAYMENT FAILED',
    headline: 'Payment failed for {{partner.partner_name}}',
    subheadline: 'Immediate follow-up recommended',
    context_block: 'A payment for {{property.property_name}}\'s license could not be processed.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Amount', value: '${{invoice.amount}}.00' },
      { label: 'Failure Reason', value: 'Card declined' },
      { label: 'Attempts', value: '2' },
      { label: 'Next Retry', value: 'In 3 days' },
    ],
    callout: 'Suggested next step: Reach out to {{teammate.name}} to update their payment method.',
    cta_label: 'View in Stripe', cta_url: 'https://dashboard.stripe.com/invoices',
    secondary_cta_label: 'Manage License', secondary_cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'Payment failed - ${{invoice.amount}}.00 ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-renewal-30', name: 'Renewal reminder 30 days', category: 'Admin — Financial', urgency: 'warning',
    description: 'Admin notification 30 days before a license renewal.',
    trigger_function: 'notifyAdminsLicenseRenewal',
    event_tag: 'RENEWAL DUE - 30 DAYS',
    headline: '{{partner.partner_name}} renewal in 30 days',
    subheadline: 'Heads up so you can plan outreach before the renewal date.',
    context_block: 'The license for {{property.property_name}} is scheduled to renew on {{invoice.renewal_date}}.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Renewal Date', value: '{{invoice.renewal_date}}' },
      { label: 'Annual Fee', value: '${{invoice.amount}}' },
      { label: 'Auto-Renew', value: 'Yes' },
    ],
    cta_label: 'View License', cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'Renewal in 30 days - {{partner.partner_name}} ({{property.property_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-renewal-14', name: 'Renewal reminder 14 days', category: 'Admin — Financial', urgency: 'warning',
    description: 'Admin notification 14 days before a license renewal.',
    trigger_function: 'notifyAdminsLicenseRenewal',
    event_tag: 'RENEWAL DUE - 14 DAYS',
    headline: '{{partner.partner_name}} renewal in 14 days',
    subheadline: 'Heads up so you can plan outreach before the renewal date.',
    context_block: 'The license for {{property.property_name}} is scheduled to renew on {{invoice.renewal_date}}.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Renewal Date', value: '{{invoice.renewal_date}}' },
      { label: 'Annual Fee', value: '${{invoice.amount}}' },
      { label: 'Auto-Renew', value: 'Yes' },
    ],
    cta_label: 'View License', cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'Renewal in 14 days - {{partner.partner_name}} ({{property.property_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-renewal-7', name: 'Renewal reminder 7 days', category: 'Admin — Financial', urgency: 'alert',
    description: 'Admin notification 7 days before a license renewal.',
    trigger_function: 'notifyAdminsLicenseRenewal',
    event_tag: 'RENEWAL DUE - 7 DAYS',
    headline: '{{partner.partner_name}} renewal in 7 days',
    subheadline: 'This renewal is coming up soon. Confirm the partner is ready.',
    context_block: 'The license for {{property.property_name}} is scheduled to renew on {{invoice.renewal_date}}.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Renewal Date', value: '{{invoice.renewal_date}}' },
      { label: 'Annual Fee', value: '${{invoice.amount}}' },
      { label: 'Auto-Renew', value: 'No' },
    ],
    cta_label: 'View License', cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'Renewal in 7 days - {{partner.partner_name}} ({{property.property_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-license-expired', name: 'License expired', category: 'Admin — Financial', urgency: 'alert',
    description: 'Admin notification when a license expires and the property goes off-market.',
    trigger_function: 'notifyAdminsLicenseExpired',
    event_tag: 'LICENSE EXPIRED',
    headline: 'License expired for {{partner.partner_name}}',
    subheadline: 'The property has been taken off-market. Follow up with the partner about renewal.',
    context_block: 'The license for {{property.property_name}} expired and the property has been automatically marked as inactive.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'License Number', value: '{{invoice.license_number}}' },
      { label: 'Annual Fee', value: '${{invoice.amount}}' },
      { label: 'Days Past Due', value: '1' },
    ],
    callout: 'Suggested next step: Contact the partner to confirm renewal intent or initiate offboarding.',
    cta_label: 'View License', cta_url: 'https://100c-os.base44.app/Licenses',
    subject: 'License expired - {{property.property_name}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-property-paused', name: 'Property paused/off-market', category: 'Admin — Financial', urgency: 'warning',
    description: 'Admin notification when a partner pauses a property.',
    trigger_function: 'notifyAdminsPropertyPaused',
    event_tag: 'PROPERTY PAUSED',
    headline: '{{property.property_name}} was paused by {{partner.partner_name}}',
    subheadline: 'The partner paused this property. It is no longer bookable on the site.',
    context_block: '{{partner.partner_name}} changed the status of {{property.property_name}} to paused. The listing has been removed from the public site.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Market', value: '{{property.location}}' },
      { label: 'Previous Status', value: 'Active' },
      { label: 'New Status', value: 'Paused' },
      { label: 'Changed By', value: '{{inviter.name}}' },
    ],
    cta_label: 'View Property', cta_url: 'https://100c-os.base44.app/Properties',
    subject: 'Property paused - {{property.property_name}} ({{partner.partner_name}})',
    reply_prompt_enabled: false,
  },

  // ══ Admin - Digests (3) ══════════════════════════════════════════════
  {
    slug: 'daily-digest', name: 'Daily briefing', category: 'Admin — Digests', urgency: 'default',
    description: "Daily summary of yesterday's activity across applications, submissions, payments, and jobs.",
    trigger_function: 'dailyAdminDigest',
    event_tag: 'DAILY BRIEFING',
    headline: 'Yesterday at The 100 Collection',
    subheadline: 'Thursday, July 16',
    context_block: "Here is a quick rundown of yesterday's activity.",
    sections: [
      { title: 'You received 3 new applications', data_rows: [{ label: 'Seaside Vacations', value: 'Property Manager' }, { label: 'Coastal Retreats LLC', value: 'Property Manager' }, { label: 'Buck Cumbo', value: 'Property Owner' }] },
      { title: 'You received 2 new property submissions', data_rows: [{ label: 'Test Partner Co', value: 'Test Villa Estate' }, { label: 'Seaside Vacations', value: 'Oceanview Penthouse' }] },
      { title: 'You collected 4 payments totaling $1,992', data_rows: [{ label: 'Test Partner Co', value: '$498' }, { label: 'Coastal Retreats', value: '$498' }, { label: 'Outer Banks Rentals', value: '$498' }, { label: 'Seaside Vacations', value: '$498' }] },
      { title: 'No payment failures', data_rows: [] },
      { title: '2 new portal signups', data_rows: [{ label: 'Seaside Vacations', value: 'admin@seaside.com' }, { label: 'Coastal Retreats', value: 'info@coastalretreats.com' }] },
      { title: '1 job posting closed', data_rows: [{ label: 'Test Partner Co', value: 'Guest Services Manager (Filled)' }] },
    ],
    cta_label: 'Open Admin Hub', cta_url: ADMIN_HUB,
    subject: 'Daily briefing - Thursday, July 16',
    reply_prompt_enabled: false,
  },
  {
    slug: 'weekly-digest', name: 'Weekly Monday digest', category: 'Admin — Digests', urgency: 'default',
    description: "Weekly summary of the past week's activity across partners, properties, and revenue.",
    trigger_function: 'weeklyAdminDigest',
    event_tag: 'WEEKLY DIGEST',
    headline: 'Last week at The 100 Collection',
    subheadline: 'July 7 to July 13',
    context_block: 'Here is your weekly rhythm summary across partners, properties, and revenue.',
    hero_image_url: MOCK_PROPERTY_HERO,
    sections: [
      { title: '12 new applications this week', data_rows: [{ label: 'Seaside Vacations', value: 'Property Manager' }, { label: 'Coastal Retreats LLC', value: 'Property Manager' }, { label: 'Buck Cumbo', value: 'Property Owner' }, { label: 'Oceanfront Properties', value: 'Property Manager' }] },
      { title: '8 new property submissions', data_rows: [{ label: 'Test Partner Co', value: 'Test Villa Estate' }, { label: 'Seaside Vacations', value: 'Oceanview Penthouse' }, { label: 'Coastal Retreats', value: 'Beachfront Cottage' }] },
      { title: '18 payments collected totaling $8,964', data_rows: [{ label: 'Test Partner Co', value: '$498' }, { label: 'Seaside Vacations', value: '$996' }, { label: 'Coastal Retreats', value: '$498' }] },
      { title: '3 new partners went live', data_rows: [{ label: 'Seaside Vacations', value: 'Nags Head, NC' }, { label: 'Coastal Retreats', value: 'Kill Devil Hills, NC' }, { label: 'Oceanfront Properties', value: 'Kitty Hawk, NC' }] },
      { title: '2 payment failures need attention', data_rows: [{ label: 'Outer Banks Rentals', value: 'Card declined' }, { label: 'Beachfront Co', value: 'Insufficient funds' }] },
      { title: '5 job postings closed', data_rows: [{ label: 'Test Partner Co', value: 'Guest Services Manager (Filled)' }, { label: 'Seaside Vacations', value: 'Housekeeper (Closed)' }] },
    ],
    cta_label: 'Open Admin Hub', cta_url: ADMIN_HUB,
    subject: 'Weekly digest - July 7 to July 13',
    reply_prompt_enabled: false,
  },
  {
    slug: 'monthly-billing-summary', name: 'Monthly billing summary', category: 'Admin — Digests', urgency: 'default',
    description: 'Monthly financial summary with revenue, license counts, and billing health.',
    trigger_function: 'monthlyBillingSummary',
    event_tag: 'MONTHLY BILLING SUMMARY',
    headline: 'June billing summary',
    subheadline: 'June 1 to June 30',
    context_block: 'Here is your monthly financial rhythm and billing health summary.',
    sections: [
      { title: 'Revenue collected: $42,834', data_rows: [{ label: 'License fees', value: '$38,346' }, { label: 'Onboarding fees', value: '$4,488' }, { label: 'Outstanding', value: '$2,988' }] },
      { title: '64 active licenses', data_rows: [{ label: 'New this month', value: '8' }, { label: 'Renewed', value: '12' }, { label: 'Expired', value: '2' }, { label: 'Avg annual fee', value: '$498' }] },
      { title: 'Payment health', data_rows: [{ label: 'Successful payments', value: '52' }, { label: 'Failed payments', value: '6' }, { label: 'Success rate', value: '89.7%' }, { label: 'Recovery rate', value: '83%' }] },
      { title: '4 partners need billing follow-up', data_rows: [{ label: 'Outer Banks Rentals', value: '2 failed payments' }, { label: 'Beachfront Co', value: 'Overdue invoice' }, { label: 'Coastal Retreats', value: 'Expired card' }, { label: 'Seaside Vacations', value: 'Pending renewal' }] },
      { title: 'Upcoming renewals (next 30 days)', data_rows: [{ label: 'Test Partner Co', value: 'Aug 16 - $498' }, { label: 'Seaside Vacations', value: 'Aug 22 - $996' }, { label: 'Coastal Retreats', value: 'Aug 28 - $498' }] },
    ],
    cta_label: 'Open Billing', cta_url: 'https://100c-os.base44.app/Billing',
    subject: 'Monthly billing summary - June 2026',
    reply_prompt_enabled: false,
  },

  // ══ Offboarding (6) ══════════════════════════════════════════════════
  {
    slug: 'offboard-paused-partner-confirmation', name: 'Property paused - partner confirmation', category: 'Offboarding', urgency: 'warning',
    description: 'Sent to a partner when they take a property offline temporarily.',
    trigger_function: 'manageOffboarding',
    event_tag: 'PROPERTY OFFLINE',
    headline: 'Your property is offline',
    subheadline: '{{property.property_name}} has been taken offline temporarily.',
    context_block: "We've hidden {{property.property_name}} from theonehundredcollection.com. Your license remains active and you can bring the property back online anytime from your Partner Portal.",
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Status', value: 'Temporarily Offline' },
      { label: 'License', value: 'Still Active' },
    ],
    cta_label: 'Bring back online', cta_url: PORTAL_URL,
    subject: 'Your property is offline',
    reply_prompt_enabled: false,
  },
  {
    slug: 'offboard-scheduled-partner-confirmation', name: 'Offboarding scheduled - partner confirmation', category: 'Offboarding', urgency: 'warning',
    description: 'Sent to a partner when they schedule a future offboarding date for their property.',
    trigger_function: 'manageOffboarding',
    event_tag: 'OFFBOARDING SCHEDULED',
    headline: 'Offboarding Scheduled',
    subheadline: '{{property.property_name}} will be offboarded on the scheduled date.',
    context_block: 'Your property remains live on theonehundredcollection.com until the scheduled date. On that date, it will automatically move to inactive status. You can cancel this scheduled offboarding anytime from your Partner Portal.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Termination Date', value: '{{invoice.renewal_date}}' },
    ],
    cta_label: 'Manage in Portal', cta_url: PORTAL_URL,
    subject: 'Offboarding Scheduled',
    reply_prompt_enabled: false,
  },
  {
    slug: 'offboard-termination-request-received', name: 'Termination request received - partner confirmation', category: 'Offboarding', urgency: 'default',
    description: 'Sent to a partner when they submit a termination request for admin review.',
    trigger_function: 'manageOffboarding',
    event_tag: 'TERMINATION REQUEST RECEIVED',
    headline: 'Termination Request Received',
    subheadline: "We've received your request to terminate {{property.property_name}}.",
    context_block: 'Our team will review your request and get back to you within 2 business days. Your property remains active until we confirm the termination.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Status', value: 'Pending Review' },
    ],
    subject: 'Termination Request Received',
    reply_prompt_enabled: false,
  },
  {
    slug: 'offboard-termination-approved', name: 'Termination approved - partner confirmation', category: 'Offboarding', urgency: 'default',
    description: 'Sent to a partner when their termination request is approved and the property is offboarded.',
    trigger_function: 'manageOffboarding',
    event_tag: 'TERMINATION COMPLETE',
    headline: '{{property.property_name}} has been offboarded',
    subheadline: 'Termination complete.',
    context_block: 'Your termination request for {{property.property_name}} has been approved. The property has been removed from theonehundredcollection.com and the associated license has been cancelled. Our team will be in touch about any pending billing adjustments. Thank you for the time we spent together in the Collection.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Effective', value: 'Immediately' },
      { label: 'License', value: 'Cancelled' },
    ],
    subject: '{{property.property_name}} has been offboarded',
    reply_prompt_enabled: false,
  },
  {
    slug: 'offboard-auto-terminated', name: 'Scheduled offboarding complete - partner confirmation', category: 'Offboarding', urgency: 'default',
    description: 'Sent to a partner when a scheduled offboarding is automatically processed on the termination date.',
    trigger_function: 'processScheduledOffboardings',
    event_tag: 'OFFBOARDING COMPLETE',
    headline: '{{property.property_name}} has been offboarded',
    subheadline: 'Your scheduled offboarding is now complete.',
    context_block: 'As scheduled, {{property.property_name}} has been offboarded from The 100 Collection today. The property has been removed from theonehundredcollection.com and the associated license has been cancelled. Thank you for your partnership.',
    data_rows: [
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Offboarded', value: '{{invoice.renewal_date}}' },
    ],
    subject: '{{property.property_name}} has been offboarded',
    reply_prompt_enabled: false,
  },
  {
    slug: 'admin-offboard-termination-request', name: 'Termination request - admin notification', category: 'Offboarding', urgency: 'alert',
    description: 'Admin notification when a partner requests permanent termination of a property.',
    trigger_function: 'manageOffboarding',
    event_tag: 'TERMINATION REQUEST',
    headline: '{{partner.partner_name}} requested termination of {{property.property_name}}',
    subheadline: 'Termination requires your approval.',
    data_rows: [
      { label: 'Partner', value: '{{partner.partner_name}}' },
      { label: 'Property', value: '{{property.property_name}}' },
      { label: 'Reason', value: '{{submission.partner_facing_message}}' },
    ],
    callout: 'Approving this will fully terminate the property, cancel the license, and depublish from theonehundredcollection.com.',
    cta_label: 'Review in Admin Hub', cta_url: `${ADMIN_HUB}?tab=offboarding`,
    subject: 'Termination request: {{partner.partner_name}} / {{property.property_name}}',
    reply_prompt_enabled: false,
  },

  // ══ Auto-reply (1) ════════════════════════════════════════════════════
  {
    slug: 'partner-application-auto-reply', name: 'PartnerApplication auto-reply to applicant', category: 'Auto-reply', urgency: 'default',
    description: 'Auto-reply sent to applicants after they submit a partner application.',
    trigger_function: 'matchExistingPartnerRequest',
    event_tag: 'APPLICATION RECEIVED',
    headline: 'Thank you for your interest in The 100 Collection',
    subheadline: 'Your application is under review.',
    context_block: 'Hi {{application.full_name}}, thank you for applying to join The 100 Collection. We have received your application and our team will review it carefully. If your properties are a good fit for our curated collection, we will reach out within 3 to 5 business days to schedule an introductory call.',
    cta_label: 'Explore The 100 Collection', cta_url: 'https://theonehundredcollection.com',
    subject: 'Thank you for your interest in The 100 Collection',
    hero_image_url: MOCK_DESTINATION_HERO,
    what_happens_next: WHAT_HAPPENS_NEXT.application,
    social_proof: SOCIAL_PROOF.application,
    reply_prompt_enabled: true,
  },
];

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Fetch existing slugs to skip (idempotent)
    const existing = await base44.asServiceRole.entities.EmailTemplate.filter({}, '-created_date', 200);
    const existingSlugs = new Set((existing || []).map(t => t.slug));

    const toCreate = TEMPLATES.filter(t => !existingSlugs.has(t.slug));
    const skipped = TEMPLATES.length - toCreate.length;

    let created = 0;
    const errors = [];

    // Create in batches of 20
    for (let i = 0; i < toCreate.length; i += 20) {
      const batch = toCreate.slice(i, i + 20);
      try {
        const records = batch.map(t => ({
          ...t,
          status: 'active',
          reply_prompt_enabled: t.reply_prompt_enabled !== false,
          data_rows: t.data_rows || [],
          what_happens_next: t.what_happens_next || [],
          sections: t.sections || [],
        }));
        await base44.asServiceRole.entities.EmailTemplate.bulkCreate(records);
        created += records.length;
      } catch (err) {
        errors.push({ batch: i, error: err.message });
      }
    }

    return Response.json({
      total_templates: TEMPLATES.length,
      already_existed: skipped,
      created,
      errors,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}